Feature/add is default flag to address
fond-of/spryker-jellyfish-b2b pull request #4
Opened 2020-11-23 16:01 UTC by gengjozsef

2020-11-23 19:45 UTC, julianzimmermann approved these changes

2020-11-23 19:45 UTC, julianzimmermann commented on src/FondOfSpryker/Zed/JellyfishB2B/Business/JellyfishB2BBusinessFactory.php
> +
remove new line

2020-11-24 08:33 UTC, daniel-rose requested changes

2020-11-24 08:33 UTC, daniel-rose commented on src/FondOfSpryker/Zed/JellyfishB2B/Communication/Plugin/JellyfishCompanyBusinessUnitDefaultAddressExpanderPlugin.php
> +
remove new line

2020-11-24 10:03 UTC, gengjozsef commented on src/FondOfSpryker/Zed/JellyfishB2B/Communication/Plugin/JellyfishCompanyBusinessUnitDefaultAddressExpanderPlugin.php
> +
done

2020-11-24 10:03 UTC, gengjozsef commented on src/FondOfSpryker/Zed/JellyfishB2B/Business/JellyfishB2BBusinessFactory.php
> +
done

2020-11-24 10:32 UTC, daniel-rose approved these changes

2020-11-24 10:48 UTC, merged